---

- name: Provision a web server
  hosts: webservers
  become: yes
  become_user: nginx
  remote_user: nginx
  vars:
    update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/webservers.yml

  roles:
    - nginx
