---
- name: Remove default configuration
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{nginx_sites_available_dir}}/default"
    - "{{nginx_sites_enabled_dir}}/default"
    - "{{nginx_conf_dir}}/conf.d/default.conf"

- name: Register enabled sites
  shell: ls -1 {{ nginx_sites_enabled_dir }} || true
  register: nginx_sites_enabled_all
  changed_when: False

- name: Copy Nginx configuration
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_file }}"
    backup: yes

- name: Copy available sites configuration
  template:
    src: nginx.site.j2
    dest: "{{ nginx_sites_available_dir }}/{{ item.key }}"
    backup: yes
  with_dict: "{{ nginx_sites }}"

- name: Symlink Nginx enabled sites
  file:
    src: "{{ nginx_sites_available_dir }}/{{ item }}"
    dest: "{{ nginx_sites_enabled_dir }}/{{ item }}"
    state: link
  with_items: "{{ nginx_sites_enabled }}"
  notify: Reload Nginx

- name: Remove rogue/disabled Nginx sites
  file:
    path: "{{ nginx_sites_enabled_dir }}/{{ item }}"
    state: absent
  with_items: "{{ (nginx_sites_enabled_all.stdout_lines | union(nginx_sites_available)) | difference(nginx_sites_enabled) }}"
  notify: Reload Nginx
