---
- name: Validate Nginx configuration
  shell: "{{ nginx_binary_name }} -t"
  register: result
  changed_when: "result.rc != 0"
  always_run: yes

- name: Start Nginx
  service:
    name: "{{ nginx_service_name }}"
    state: started
    enabled: yes
