version: '2'

services:
  # LDAP
  openldap:
    build: ./openldap
    container_name: openldap
    environment:
      LDAP_ORGANISATION: "example"
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "password"
    ports:
      - "10389:389"
  # LDAP Management Tool
  phpldapadmin:
    image: osixia/phpldapadmin:0.7.1
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "10080:80"
    links:
      - "openldap:ldap"
  # VCS(SCM)
  gitlab:
    build: ./gitlab
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
    ports:
      - '10082:80'
      - '10433:433'
    links:
      - "openldap:ldap"
  # Issue Tracker
  redmine:
    image: redmine:3.4.3
    container_name: redmine
    ports:
      - '13000:3000'
    links:
      - "openldap:ldap"
  # Chat
  mattermost:
    build: ./mattermost
    container_name: mattermost
    ports:
      - '18065:8065'
    links:
      - "gitlab:scm"
  # CI Management
  jenkins:
    image: jenkins/jenkins:2.95
    container_name: jenkins
    ports:
      - '18080:8080'
      - '50000:50000'
    links:
      - "openldap:ldap"
  # Repository Management
  nexus:
    image: sonatype/nexus3:3.6.2
    container_name: nexus
    ports:
      - '18081:8081'
    links:
      - "openldap:ldap"
  # Quality Management(& Report)
  sonarqube:
    build: ./sonarqube
    container_name: sonarqube
    ports:
      - '19000:9000'
    links:
      - "openldap:ldap"
  proxy:
    build: proxy
    links:
      - openldap:openldap
      - phpldapadmin:phpldapadmin
      - gitlab:gitlab
      - redmine:redmine
      - mattermost:mattermost
      - jenkins:jenkins
      - nexus:nexus
    ports:
      - "80:80"
      - "443:443"