---
- name: Reload Nginx
  service:
    name: "{{ nginx_service_name }}"
    state: reloaded
    enabled: yes

- name: Restart Nginx
  service:
    name: "{{ nginx_service_name }}"
    state: restarted
    enabled: yes
